export const SET_NEWS = 'SET_NEWS'

export const SET_COMPANIES = 'SET_COMPANIES'

export const SET_ENTREPRENEURS = 'SET_ENTREPRENEURS'

export const SET_NEWS_TOTAL = 'SET_NEWS_TOTAL'

export const SET_COMPANIES_TOTAL = 'SET_COMPANIES_TOTAL'

export const SET_ENTREPRENEURS_TOTAL = 'SET_ENTREPRENEURS_TOTAL'
